FROM nvcr.io/nvidia/cuda:13.0.2-runtime-ubuntu24.04

ARG ARCH=arm64
ARG JETPACK=false
ARG JETPACK_MAJOR=unknown
ARG PROXY

ENV DEBIAN_FRONTEND=noninteractive
ENV OLLAMA_LLM_LIBRARY=cuda_v13

RUN chmod 1777 /tmp && apt-get update && apt-get install -y \
    curl wget ca-certificates \
    tar zstd \
    && update-ca-certificates && rm -rf /var/lib/apt/lists/*

# COPY ollama/ /tmp/

# 通用包（.tar.zst）
ARG GH_MIRROR=https://ghfast.top

RUN set -eux; \
    URL="https://ollama.com/download/ollama-linux-${ARCH}.tar.zst"; \
    echo "Downloading Ollama tar.zst from ${URL} ..."; \
    for i in 1 2 3 4 5; do \
      if [ -n "${PROXY:-}" ]; then \
        echo "using proxy ${PROXY:-<unset>}"; \
        http_proxy="${PROXY:-}" https_proxy="${PROXY:-}" \
        HTTP_PROXY="${PROXY:-}" HTTPS_PROXY="${PROXY:-}" \
        wget -O /tmp/ollama.tar.zst \
        --timeout=30 --tries=3 \
        --retry-on-http-error=429,500,502,503,504 \
        --no-cache --no-cookies --server-response \
        "$URL" && break; \
      else \
        REAL_URL=$(wget --spider --server-response "$URL" 2>&1 \
          | grep -i 'Location:' | tail -1 | awk '{print $2}' | tr -d '\r'); \
        DL_URL="$URL"; \
        if echo "$REAL_URL" | grep -q 'github\.com'; then \
          echo "redirected to github.com: ${REAL_URL}"; \
          DL_URL="${GH_MIRROR}/${REAL_URL}"; \
          echo "using github mirror: ${DL_URL}"; \
        fi; \
        wget -O /tmp/ollama.tar.zst \
        --timeout=30 --tries=3 \
        --retry-on-http-error=429,500,502,503,504 \
        --no-cache --no-cookies --server-response \
        "$DL_URL" && break; \
      fi; \
      echo "retry $i ..."; sleep 2; \
      rm -f /tmp/ollama.tar.zst; \
    done; \
    test -s /tmp/ollama.tar.zst; \
    mkdir -p /usr/local/ollama; \
    tar --zstd -xf /tmp/ollama.tar.zst -C /usr/local/ollama; \
    ln -sf /usr/local/ollama/bin/ollama /usr/local/bin/ollama; \
    chmod +x /usr/local/ollama/bin/ollama


# ✅ 清除构建期代理环境变量
ENV http_proxy= \
    https_proxy= \
    HTTP_PROXY= \
    HTTPS_PROXY= \
    no_proxy= \
    NO_PROXY=

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip \
  && rm -rf /var/lib/apt/lists/*

# 复制 gateway 文件
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip3 install --break-system-packages --no-cache-dir -i https://mirrors.ustc.edu.cn/pypi/simple -r /app/requirements.txt

COPY gateway.py /app/gateway.py
COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh

# 暴露端口：对外只需要 Gateway 端口
EXPOSE 11535

# Redis 配置（你也可以放到 compose 里传）
ENV REDIS_HOST=172.28.1.1 \
    REDIS_PORT=6379 \
    REDIS_USER=default \
    REDIS_PASSWORD=Rr123456 \
    UPSTREAM_BASE=http://127.0.0.1:11434

CMD ["/app/start.sh"]