name: ollama_server_test

services:
  redis:
    image: redis:7-alpine
    container_name: ollama-redis-test
    command: redis-server --requirepass "$REDIS_PASSWORD"
    env_file:
      - ../.env
    volumes:
      - redis-data:/data
    ports:
      - "$REDIS_PORT:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        OLLAMA_TAG: ${OLLAMA_TAG:-latest}
    image: ollama-gateway:${OLLAMA_TAG:-latest}
    container_name: ollama-gateway-test
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        /bin/bash /app/tests/test.sh
    ports:
      - "11535:11535"
    env_file:
      - ../.env
    environment:
      TEST_MODEL: ${TEST_MODEL:-qwen3:0.6b}
      PYTHONPATH: /app
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      OLLAMA_CONTEXT_LENGTH: "8192"
    depends_on:
      redis:
        condition: service_healthy
    restart: no
    volumes:
      - ollama-test:/root/.ollama
      - ..:/app
      # - /run/jtop.sock:/run/jtop.sock
      # - /usr/bin/tegrastats:/usr/bin/tegrastats:ro
      # - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra
    runtime: nvidia

volumes:
  ollama-test:
  redis-data:

networks:
  default:
    name: ollama-test-network
