name: ollama_server_test

services:
  gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        OLLAMA_TAG: ${OLLAMA_TAG:-latest}
    image: ollama_server:${OLLAMA_TAG:-latest}
    container_name: ollama_server-test
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        /bin/bash /app/tests/test.sh
    ports:
      - "11535:11535"
    env_file:
      - ../.env
    environment:
      TEST_MODEL: ${TEST_MODEL:-qwen3:0.6b}
      PYTHONPATH: /app
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      OLLAMA_CONTEXT_LENGTH: "8192"
    restart: no
    volumes:
      - ollama-test:/root/.ollama
      - ..:/app
      # - /run/jtop.sock:/run/jtop.sock
      # - /usr/bin/tegrastats:/usr/bin/tegrastats:ro
      # - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra
    runtime: nvidia

volumes:
  ollama-test:

networks:
  default:
    name: ollama-test-network
